# Generated by Django 5.1.2 on 2024-10-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='qr_image',
        ),
        migrations.CreateModel(
            name='QRImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(default='qr.png', upload_to='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.qr')),
            ],
        ),
    ]
