# Generated by Django 5.1.2 on 2024-10-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrimage',
            name='connection',
        ),
        migrations.DeleteModel(
            name='QR',
        ),
        migrations.DeleteModel(
            name='QRImage',
        ),
    ]
